DROP TABLE IF EXISTS websites CASCADE;

CREATE TABLE websites (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  url VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  loginName VARCHAR(255) NOT NULL,
  category_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  icon VARCHAR(255)
);
